@startuml

class TaskManager
note right: 负责统领和协调数据爬取的流程
interface CrawlingTargetModule
note bottom: 负责给出基金爬取任务(要爬哪些基金)
interface DataMiningModule
note bottom: 负责http返回的解析(清洗基金数据)
interface SavingResultModule
note bottom: 负责爬取结果保存
class GetPageByMultiThreading
note bottom: 负责http的下载

TaskManager .down.> CrawlingTargetModule
TaskManager .down.> DataMiningModule
TaskManager .down.> SavingResultModule
TaskManager .down.> GetPageByMultiThreading

class RateControl
note bottom: http下载的负载均衡
class FakeUA
note bottom: 提供随机ua

GetPageByMultiThreading .down.> RateControl
GetPageByMultiThreading .down.> FakeUA

class GetFundByWeb
note bottom: 获取全部的基金列表
class GetSmallBatch4Test
note bottom: 获取部分的基金列表
class GetSpecialFund
note bottom: 提供指定的若干个基金
CrawlingTargetModule ^-down- GetFundByWeb
CrawlingTargetModule ^-down- GetSmallBatch4Test
CrawlingTargetModule ^-down- GetSpecialFund

class DataMining
note bottom: 负责http返回的解析(清洗基金数据)
DataMiningModule ^-down- DataMining
class DataCleaningStrategyFactory
DataMining .down.> DataCleaningStrategyFactory
DataCleaningStrategyFactory .down.> DataCleaningStrategy
interface DataCleaningStrategy
note bottom: 页面解析策略(给出页面url和对应的解析结果)
class MorningstarStrategy
note bottom: 晨星特有代码的解析
class ManagerStrategy
note bottom: 基金经理页面的解析
class OverviewStrategy
note bottom: 基金概况页面的解析
class RiskStrategy
note bottom: 风险相关数据的解析
class ReturnStrategy
note bottom: 回报相关数据的解析
DataCleaningStrategy ^-down- MorningstarStrategy
DataCleaningStrategy ^-down- ManagerStrategy
DataCleaningStrategy ^-down- OverviewStrategy
DataCleaningStrategy ^-down- RiskStrategy
DataCleaningStrategy ^-down- ReturnStrategy

class SaveResult2CSV
note bottom: 将结果保存为csv文件
SavingResultModule ^-down- SaveResult2CSV


@enduml